### ISSUE TITLE
too good to be true

### ISSUE THREAD

**Issue by ilyamironow** [alageev/Skillfactory-news-app#1]
i think everything was copied from stackoverflow

**Comment by ilyamironow** [comment]
i think everything was copied from stackoverflow

**Comment by alageev** [comment]
![](https://i.pinimg.com/originals/72/9f/6f/729f6f5dfa9950a878b0303eb71255d9.gif)

**Comment by ilyamironow** [comment]
😂😂

**Comment by alageev** [comment]
![](https://mem-baza.ru/_ph/1/2/210280405.jpg?1600932522)

**Comment by ilyamironow** [comment]
Хахах

**Comment by ilyamironow** [comment]
![505340ed6db387d3f4b7488fbae4c7fd](https://user-images.githubusercontent.com/31896799/141784536-252333f2-acea-42d3-9518-39f7c29891c8.jpg)
